name: lst-dev
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python=3.8
  - astropy~=4.2
  - pip
  - ctapipe~=0.11
  - gammapy>=0.18
  - h5py
  - ipython
  - jupyter
  - notebook
  - joblib
  - toml
  - protozfits=2.0
  - pyparsing~=2.4
  - traitlets=5.0
  - pip:
      - pytest_runner
      - pytest-ordering
      - ctapipe_io_lst~=0.11.1
      - ctaplot
      - pyirf~=0.5.0

