name: lst-dev
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python=3.7
  - astropy>=4.2
  - pip
  - ctapipe>=0.10.3
  - gammapy>=0.18
  - h5py
  - ipython
  - jupyter
  - notebook
  - joblib
  - toml
  - pip:
      - pytest_runner
      - pytest-ordering
      - git+git://github.com/cta-observatory/ctapipe_io_lst@v0.6.5
      - ctaplot
      - astropy>=4.1
      - pyirf~=0.4.0
